export const ADD_COMMENT = 'ADD_COMMENT';
export const POSTS_LOADING = 'POSTS_LOADING';
export const POSTS_FAILED = 'POSTS_FAILED';
export const ADD_POSTS = 'ADD_POSTS';
export const CHANGE_POST_LIKE = 'CHANGE_POST_LIKE';
export const CHANGE_COMMENT1_LIKE = 'CHANGE_COMMENT1_LIKE';